version: '3.8'
services:
  katalog-app:
    build: .
    container_name: katalog-v2
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=https://katalog.161.118.172.246.nip.io
    volumes:
      # Yüklenen resimleri sunucuda kalıcı hale getiren ayar:
      - ./public/images/products:/app/public/images/products